name: firs workflow lab

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: Copy my repo
          uses: actions/checkout@v4

        - name: Welcome to my firts job
          run: "echo Hi, i am $(whoami) from my firts job and my pass is: ${{ secrets.DOCKERPASS }}"