name: firs workflow lab

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: Copy my repo
          uses: actions/checkout@v4

        - name: Welcome to my firts job
          run: echo "Hi, i am $(whoami) from my firts job" > filepro.txt

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: my-artifact-filepro
            path: filepro.txt
    

    second_job:
      needs: first_job
      runs-on: ubuntu-latest
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact-filepro

      - name: List artifact
        run: ls

    third_job:
      needs: second_job
      runs-on: ubuntu-latest
      steps:
      - name: Read file
        run: ls